[package]
name = "bsuir_tgbot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15"
teloxide = { version = "0.15.0", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
